### ISSUE TITLE
derive(Template) cannot move out of borrowed content

### ISSUE THREAD

**Issue by TheWaWaR** [djc/askama#128] opened 2018-10-15 07:56 UTC
## Error: 
```
error[E0507]: cannot move out of borrowed content
   --> actix-shs-cli/src/main.rs:106:10
    |
106 | #[derive(Template)]
    |          ^^^^^^^^ cannot move out of borrowed content

error: aborting due to previous error

For more information about this error, try `rustc --explain E0507`.
error: Could not compile `actix-shs-cli`.
```

## Reproduce
``` bash
git clone https://github.com/local-group/acitx-simple-http-server.git
git checkout 1a07dc188246638028485bdd3c55315c4df54595
cargo build
```

**Comment by djc** [comment] 2018-10-15 08:14
This is pretty much a duplicate of #106, so I'll close this, and let's continue discussion there.

**Closed by djc** 2018-10-15 08:14 UTC

**Comment by TheWaWaR** [comment] 2018-10-15 08:30
Use `as_str()` will fix this, because some fields' type are `String`.

**The data strucutre:**
``` rust
struct RowItem {
    filename: String,
    linkstyle: &'static str,
    link: String,
    label: String,
    modified: String,
    filesize: String,
}
```

**The template:**
``` jinja2
{% for row in rows %}
  <tr>
    <td><a {{ row.linkstyle }} href="/{{ row.link.as_str() }}">{{ row.label.as_str() }}</a></td>
    <td style="color:#888;">[{{ row.modified.as_str() }}]</td>
    <td><bold>{{ row.filesize.as_str() }}</bold></td>
  </tr>
{% endfor %}
```

**Comment by djc** [comment] 2018-10-19 18:30
That's not a very nice workaround... I think the code generator should be able to handle this, if you can give me feedback on #133 that would be very helpful.
