### ISSUE TITLE
Template can't be turned into a trait object

### ISSUE THREAD

**Issue by dnsco** [djc/askama#238] opened 2019-05-08 03:04 UTC
First off, thanks for the crate!

Since the size_hint function has not constraints on things being sized, and has no receiver the Template trait can't be changed into a Trait Object. Could this function be moved out of this trait, or could it be turned into a method?

I would like to be able to box my templates, rather than compile with monomorphization to keep compile times down.

Thanks!

**Comment by djc** [comment] 2019-06-17 12:22
Some discussion here: https://internals.rust-lang.org/t/allowing-calling-static-methods-through-trait-objects/10417

**Comment by djc** [comment] 2019-06-17 12:35
If you'd like to add `dyn_size_hint()` method to the trait as proposed as a workaround there, I'd be happy to merge that! Should be a fairly straightforward change.

**Comment by jbg** [comment] 2019-10-27 14:58
I’m also seeing long compile times partly caused by having a lot of templates. I had a read through that thread and played around with adding a `dyn_size_hint()` method but I can’t quite understand how to do this in a backward-compatible manner.

**Comment by djc** [comment] 2019-10-28 09:51
What kind of backwards compatibility are you looking for? Let's start with a backwards-incompatible version, and then see how backwards incompatible it actually is.

**Comment by jbg** [comment] 2019-10-28 10:10
As far as I understand the discussion, the idea is to split the trait in two. One trait is object-safe and another trait contains the methods that would otherwise make the trait non-object-safe.

I think this would necessarily be a breaking change to the public API of `Template` since `size_hint()` is part of that public API.

Either `size_hint()` remains in `Template` with its current signature, which makes the trait non-object-safe, or it moves into a separate trait, which is a backward compatibility break.

**Comment by djc** [comment] 2019-10-28 10:47
But my thing is that `size_hint()` is not a very important part of `Template`, in the sense that probably a minority of users is using it other than through the integrations included in Askama. Of course I could be wrong about that... but I don't mind making a backwards-incompatible release, anyway (and based on the crates.io data, people are upgrading enough anyway). Let's move `size_hint()` to a different trait.

**Comment by jbg** [comment] 2019-10-28 10:48
OK, great. I will send a PR soon!

**Comment by jbg** [comment] 2019-10-28 12:26
I opened two PRs with different approaches.

#269 is closer to that discussion linked above. You can derive Template as normal and then do `(&tpl as &dyn TemplateDyn)` or `Box::new(tpl) as Box<dyn TemplateDyn>` to get a trait object.

#270 is a lighter change, it just moves the no-receiver `size_hint()` method into a separate trait, updates `askama_derive` to also produce impls for that trait, and if users want to get a size hint for a template without an instance they just need to import that trait.

**Comment by djc** [comment] 2019-10-28 14:47
Should be fixed by #270.

**Closed by djc** 2019-10-28 14:47 UTC
