### ISSUE TITLE
Regression for `let` in allowing variables to start with `_` (underscore)

### ISSUE THREAD

**Issue by cipriancraciun** [djc/askama#1105] opened 2024-11-14 13:47 UTC
Up to version 12 (excluding), one could have written `{% let _x = 7 %}` and have it correctly compile.  In version 12.1, it fails with:
~~~~
error: literals are not allowed on the left-hand side of an assignment
~~~~

(According to the Rust reference, identifiers are allowed to start with an `_`, as per <https://doc.rust-lang.org/reference/identifiers.html>.)

It appears that neither identifiers that start with an upper-case letter (like `X`) are allowed, with the same error.

**Comment by djc** [comment] 2024-11-15 09:17
Sorry for the regression, looks like this has been fixed on main though -- see #1035 for the upcoming 0.13 release.

**Closed by djc** 2024-11-15 09:17 UTC
